name: SuperHub
main: NinjaKnights\SuperHub\Main
version: 1.0
api: 3.0.0
mcpe-protocol: [361, 388, 389, 390, 407, 408]
author: TheKnightGamer / Jean  #Add your name here when you contribute 
description: A Super Hub plugin 
    
commands:
  test:
    description: 

permissions:
  test.all:
    default: op
    description: 