#       _____                       _    _       _
#      / ____|                     | |  | |     | |
#     | (___  _   _ _ __   ___ _ __| |__| |_   _| |__
#      \___ \| | | | '_ \ / _ \ '__|  __  | | | | '_ \
#      ____) | |_| | |_) |  __/ |  | |  | | |_| | |_) |
#     |_____/ \__,_| .__/ \___|_|  |_|  |_|\____|____/
#                  | |
#                  |_|
# ------------------ #
# | AUTO BROADCAST | #
# ------------------ #

announcements:
  # Should the announcements system be enabled ?
  enabled: true

  # Delay to send announcements (in seconds)
  delay: 60

  # How many players should be required to send announcements?
  required_players: 1

  # Announcement list
  messages:
    test1: "Test"
    test2: "Test2"
    test3: "Test3"

# ------------------- #
# | CHAT MANAGEMENT | #
# ------------------- #

command_block:
  # Should the command blocker feature be enabled?
  enabled: true

  # List of commands that will be blocked
  blocked_commands:
    - "w"
    - "list"
    - "version"

# ------------------------ #
# | WORLD EVENT SETTINGS | #
# ------------------------ #

world_settings:

  # Player
  disable_hunger_loss: true
  disable_player_pvp: true
  disable_fall_damage: true
  disable_fire_damage: true
  disable_drowning: true
  disable_void_death: true # if true the player will teleport back to spawn when he falls in the void

  # Misc
  disable_death_message: true # ????

  # Item entities
  disable_item_drop: true
  disable_item_pickup: true

  # Blocks
  disable_block_break: true
  disable_block_place: true
  disable_block_interact: true

# --------------------- #
# | PLAYER JOIN EVENT | #
# --------------------- #

join_leave_messages:
  # Should SuperHub handle join/quit messages?
  enabled: true

  join_message: "&2&l+ &6[PLAYER] &7Connected"
  quit_message: "&4&l- &6[PLAYER] &7Disconnected"

# Actions executed upon join
join_events:

  join_message:
    enabled: true
    message:
      - "test"
      - "hi"

  join_title:
    enabled: true
    title: "Welcome [PLAYER]"
    subtitle: "to SuperHub"
    fade_in: 20
    stay: 60
    fade_out: 20

  join_sound:
    enabled: true
    sound: TotemUse

  join_effect:
    enabled: true
    effect:
      - NIGHT_VISION
      - HEALTH_BOOST
    duration: 100

join_settings:
  # Should we teleport the player to the spawn point (if set) on join?
  spawn_join: true
  # Should we heal the player?
  heal: true
  # Should we extinguish the player?
  extinguish: true
  # Should we clear their inventory?
  clear_inventory: false

# ------------- #
# | LAUNCHPAD | #
# ------------- #

launchpad:
  # Should the launchpad feature be enabled ?
  enabled: true

  # Launch power for launchpad (max 4.0)
  launch_power: 1
  launch_power_y: 1

  block: Redstone Block

# --------------- #
# | DOUBLE JUMP | #
# --------------- #

double_jump:
  # Should the double jump feature be enabled?
  enabled: true

  # Launch power for double jump (max 4.0)
  launch_power_y: 0.9

# ---------------- #
# | PLAYER HIDER | #
# ---------------- #

player_hider:
  # Should the player hider feature be enabled?
  enabled: true
  # Slot the item should be given to?
  slot: 8

  not_hidden:
    material: LIME_DYE
    amount: 1
    display_name: 'Hide Players'
    lore:
      - '&7Click to hide all players!'
      - 'Testing'
      - 'another Test'

  hidden:
    material: GRAY_DYE
    amount: 1
    display_name: 'Show Players'
    lore:
      - '&7Click to show all players!'